Enhance Cloudinary CLI for Security and Optimization
cloudinary/cloudinary-cli pull request #80
Opened 2023-10-12 05:56 UTC by simran-sankhala

### Brief Summary of Changes
Addressed the potential security risk by implementing thorough input validation and sanitization for user-provided arguments and options. This helps mitigate the risk of code injection and ensures that unexpected behavior does not occur due to malicious input. Specifically, the code now validates and sanitizes user input before processing.

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [ ] New feature
- [x] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

2023-10-12 14:46 UTC, const-cloudinary requested changes
@simran-sankhala, first of all thank you for contribution!
I like your refactoring, it makes code much more organized and easier to read!

Regarding input validation, I just saw the check that user indeed specified a valid directory, which is a good thing to check! 
Are there any other things that are changed that I am missing?

Could you also add 1-2 tests covering this use case?

BTW, tests failed. Can you please check that?

See my other comments.

2023-10-12 14:46 UTC, const-cloudinary commented on cloudinary_cli/modules/upload_dir.py
> +@click.option("-f", "--folder", default="", help="The path where you want to upload the assets. The path you specify will be pre-pended to the public IDs of the uploaded assets. You can specify a who
For readability, we keep line length up to 120 chars.

2023-10-12 14:46 UTC, const-cloudinary commented on cloudinary_cli/modules/upload_dir.py
> +    options = prepare_upload_options(transformation, preset, optional_parameter, optional_parameter_parsed, folder, folder_mode)
Like! it makes code much more readable!

2023-10-13 19:41 UTC, simran-sankhala commented
sure , let me work on that test cases

2023-11-13 16:36 UTC, colbyfayock commented
@simran-sankhala do you plan on continuing to work on this?

2025-04-14 08:48 UTC, closed without merging